-- ALTER TABLE employers
-- ALTER COLUMN yearly_revenue
-- SET DATA TYPE FLOAT;
-- POSTGRES ONLY
-- ALTER TABLE employers
-- MODIFY COLUMN yearly_revenue FLOAT(5, 2);
-- MYSQL ONLY
-- ALTER TABLE users
-- ALTER COLUMN full_name
-- SET DATA TYPE VARCHAR(300); --POSTGRESS ONLY
ALTER TABLE users
MODIFY COLUMN full_name VARCHAR(300);